baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-nix"

[params]
  Name = "Jeff Bilder"
  HeaderUsername = "jeff"
  HeaderHostname = "jeffbilder.com"
  About = "info_about_you"
  ProfilePicture = "static/me.jpg"
  CvURL = "your_cv_url"
  #Email = "your_email"
  GithubID = "jeffbildz"
  LinkedInID = "https://www.linkedin.com/in/jjbilder/"
  #Mobile = "+1-201-555-0123"
  #Phone = "+1-201-555-0123"
  TwitterID = "jeffbilder"

[menu]
  [[menu.header]]
    identifier = "post"
    name = "posts"
    weight = 0
    url = "/post"
  [[menu.header]]
    parent = "post"
    name = "All Posts"
    url = "/post"
  [[menu.header]]
    parent = "post"
    name = "categories"
    url = "/categories"
  [[menu.header]]
    parent = "post"
    name = "tags"
    url = "/tags"
