baseURL = "https://jeffbilder.com/"
languageCode = "en-us"
title = "Jeff Bilder"
theme = "hugo-theme-nix"

[params]
  Name = "Jeff Bilder"
  HeaderUsername = "user"
  HeaderHostname = "jeffbilder.com"
  About = "Welcome to my website. I specialize in designing cloud architectures and automation. Feel free to browse some of the work that I've done and let me know if you'd like to collaborate."
  ProfilePicture = "me.jpg"
  GithubID = "jeffbildz"
  LinkedInID = "jjbilder"
  TwitterID = "bilderJeff"

[menu]
  [[menu.header]]
    identifier = "about"
    name = "about"
    weight = 0
    url = "/about"
  [[menu.header]]
    identifier = "post"
    name = "posts"
    weight = 0
    url = "/post"
  [[menu.header]]
    parent = "post"
    name = "All Posts"
    url = "/post"
  [[menu.header]]
    parent = "post"
    name = "categories"
    url = "/categories"
  [[menu.header]]
    parent = "post"
    name = "tags"
    url = "/tags"
